/** Query keys, shared by the query modules and the socket handlers. */
export const keys = {
  meta: ['app', 'meta'] as const,
  version: ['app', 'version'] as const,
  settings: ['settings'] as const,
  computeUsage: ['compute', 'usage'] as const,
  computeDevices: ['compute', 'devices'] as const,
  assets: ['assets'] as const,
  models: ['models'] as const,
  catalogVoices: ['models', 'catalog'] as const,
  inbox: ['models', 'inbox'] as const,
  baseModels: ['models', 'base'] as const,
  separationModels: ['models', 'separation'] as const,
  assetRepositories: ['assets', 'repositories'] as const,
  model: (id: string) => ['models', 'id', id] as const,
  presets: (voiceId?: string | null) => (voiceId ? (['presets', voiceId] as const) : (['presets'] as const)),
  separationPresets: ['separate', 'presets'] as const,
  outputs: ['outputs'] as const,
  outputList: (filter: Record<string, string | undefined>) => ['outputs', 'list', filter] as const,
  peaks: (kind: string, id: string, points: number) => ['peaks', kind, id, points] as const,
  audioFile: (id: string) => ['audio', 'file', id] as const,
  browse: (path: string) => ['audio', 'browse', path] as const,
  jobs: ['jobs'] as const,
  jobList: (filter: Record<string, string | undefined>) => ['jobs', 'list', filter] as const,
  job: (id: string) => ['jobs', 'id', id] as const,
  jobLog: (id: string) => ['jobs', 'log', id] as const,
  experiments: ['train', 'experiments'] as const,
  experiment: (name: string) => ['train', 'experiment', name] as const,
  checkpoints: (name: string) => ['train', 'checkpoints', name] as const,
  metrics: (name: string) => ['train', 'metrics', name] as const,
  liveState: ['live', 'state'] as const,
  liveDevices: ['live', 'devices'] as const,
};
