/**
 * Icons used by the application, re-exported so that ui/ stays the only place importing @lucide/vue.
 * Pass one to <AppIcon :icon="..."/>.
 */
import { createLucideIcon, type LucideIconNode } from '@lucide/vue';

export {
  Activity,
  AlertTriangle,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  AudioLines,
  AudioWaveform,
  Ban,
  Boxes,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleCheck,
  CircleHelp,
  CircleStop,
  CircleX,
  Clock,
  Copy,
  Cpu,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileText,
  FlaskConical,
  Folder,
  FolderInput,
  FolderOpen,
  FolderUp,
  Gauge,
  GraduationCap,
  Hammer,
  HardDrive,
  Headphones,
  History,
  Info,
  KeyRound,
  Keyboard,
  Layers,
  Library,
  ListChecks,
  ListFilter,
  Loader2,
  MemoryStick,
  Merge,
  Mic,
  Minus,
  Moon,
  MoreVertical,
  Music,
  PackageOpen,
  Palette,
  Pause,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  Repeat,
  RotateCcw,
  Save,
  Scissors,
  Search,
  Server,
  Settings,
  SlidersHorizontal,
  Speaker,
  Split,
  Square,
  Sun,
  SunMoon,
  Tag,
  Timer,
  Trash2,
  Unplug,
  Upload,
  Volume2,
  Waves,
  X,
} from '@lucide/vue';

// The app's own mark: a voice turning into a waveform, drawn in Lucide's grid and stroke so it sits
// with the other icons. The favicon is the same mark.
const MARK: LucideIconNode[] = [
  ['path', { d: 'M3 12h2', key: 'a' }],
  ['path', { d: 'M7 8v8', key: 'b' }],
  ['path', { d: 'M11 4v16', key: 'c' }],
  ['path', { d: 'M15 7v10', key: 'd' }],
  ['path', { d: 'M19 10v4', key: 'e' }],
  ['path', { d: 'M21 12h0', key: 'f' }],
];
export const Mark = createLucideIcon('rvc-mark', MARK);
